apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: house-price-api
  template:
    metadata:
      labels:
        app: house-price-api
    spec:
      containers:
        - name: house-price-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
