apiVersion: v1
kind: Service
metadata:
  name: house-price-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: house-price-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
