version: "3.8"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: vuvanthanhtb/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # - ~/.kube/config:/var/jenkins_home/.kube/config
    environment:
      - KUBECONFIG=/var/jenkins_home/.kube/config

volumes:
  jenkins_home:
